// lazyload config

var jp_config = {
  easyPieChart:   [   'https://24bp.cn/404/jquery.easypiechart.fill.js'],
  sparkline:      [   'https://24bp.cn/404/jquery.sparkline.retina.js'],
  plot:           [   'https://24bp.cn/404/jquery.flot.js',
                      'https://24bp.cn/404/jquery.flot.pie.js', 
                      'https://24bp.cn/404/jquery.flot.resize.js',
                      'https://24bp.cn/404/jquery.flot.tooltip.js',
                      'https://24bp.cn/404/jquery.flot.orderBars.js',
                      'https://24bp.cn/404/jquery.flot.spline.js'],
  moment:         [   'https://24bp.cn/404/moment.js'],
  screenfull:     [   'https://24bp.cn/404/screenfull.min.js'],
  slimScroll:     [   'https://24bp.cn/404/jquery.slimscroll.min.js'],
  sortable:       [   'https://24bp.cn/404/jquery.sortable.js'],
  nestable:       [   'https://24bp.cn/404/jquery.nestable.js',
                      'https://24bp.cn/404/jquery.nestable.css'],
  filestyle:      [   'https://24bp.cn/404/bootstrap-filestyle.js'],
  slider:         [   'https://24bp.cn/404/bootstrap-slider.js',
                      'https://24bp.cn/404/bootstrap-slider.css'],
  chosen:         [   'https://24bp.cn/404/chosen.jquery.min.js',
                      'https://24bp.cn/404/bootstrap-chosen.css'],
  TouchSpin:      [   'https://24bp.cn/404/jquery.bootstrap-touchspin.min.js',
                      'https://24bp.cn/404/jquery.bootstrap-touchspin.min.css'],
  wysiwyg:        [   'https://24bp.cn/404/bootstrap-wysiwyg.js',
                      'https://24bp.cn/404/jquery.hotkeys.js'],
  dataTable:      [   'https://24bp.cn/404/jquery.dataTables.min.js',
                      'https://24bp.cn/404/dataTables.bootstrap.js',
                      'https://24bp.cn/404/dataTables.bootstrap.css'],
  vectorMap:      [   'https://24bp.cn/404/jquery-jvectormap-1.2.2.min.js', 
                      'https://24bp.cn/404/jquery-jvectormap-world-mill-en.js',
                      'https://24bp.cn/404/jquery-jvectormap-us-aea-en.js',
                      'https://24bp.cn/404/jquery-jvectormap-1.2.2.css'],
  footable:       [   'https://24bp.cn/404/footable.all.min.js',
                      'https://24bp.cn/404/footable.core.css'],
  fullcalendar:   [   'https://24bp.cn/404/moment.js',
                      'https://24bp.cn/404/fullcalendar.min.js',
                      'https://24bp.cn/404/fullcalendar.css',
                      'https://24bp.cn/404/fullcalendar.theme.css'],
  daterangepicker:[   'https://24bp.cn/404/moment.js',
                      'https://24bp.cn/404/daterangepicker.js',
                      'https://24bp.cn/404/daterangepicker-bs3.css'],
  tagsinput:      [   'https://24bp.cn/404/bootstrap-tagsinput.js',
                      'https://24bp.cn/404/bootstrap-tagsinput.css']
                      
};